echo "Setting up Git";
sudo apt install git;
git config --global user.email "timlev@gmail.com";
git config --global user.name "Tim Leverentz";
git config --global push.default simple;
cd ~/;
mkdir GitProjects;
cd GitProjects;
echo "Cloning all Github Projects";
git clone https://github.com/timlev/Bowls.git;
git clone https://github.com/timlev/Sound-Spelling.git;
git clone https://github.com/timlev/Crowd_Recorder.git;
git clone https://github.com/timlev/Drag_n_Drop.git;
git clone https://github.com/timlev/eartrainer.git;
git clone https://github.com/timlev/Learning-English.git;
git clone https://github.com/timlev/Learning-English-HTML.git;
cd Learning-English-HTML;
git checkout -b gh-pages origin/gh-pages;
cd ..;
git clone https://github.com/timlev/Proxy-Hours.git;
git clone https://github.com/timlev/read-story.git;
cd read-story;
git checkout -b gh-pages origin/gh-pages;
cd ..;
git clone https://github.com/timlev/sound_board.git;
git clone https://github.com/timlev/timlev.github.io.git;
git clone https://timlev@bitbucket.org/timlev/high-frequency-word-master.git;
git clone https://timlev@bitbucket.org/timlev/sampleextension.git;
echo "Updating GitProjects in home dir";
cd ~/GitProjects;
cd Bowls;
git pull;
cd ../Crowd_Recorder;
git pull;
cd ../Drag_n_Drop;
git pull;
cd ../eartrainer;
git pull;
cd ../Learning-English;
git pull;
cd ../Learning-English-HTML;
git pull;
cd ../Proxy-Hours;
git pull;
cd ../read-story;
git pull;
cd ../sound_board;
git pull;
cd ../timlev.github.io;
git pull;
cd ../high-frequency-word-master;
git pull;
cd ../sampleextension;
git pull;
