sudo apt install git;
git config --global user.email "timlev@gmail.com";
git config --global user.name "Tim Leverentz";
git config --global push.default simple;
cd ~/;
mkdir GitProjects;
cd GitProjects;
git clone https://github.com/timlev/timlev.github.io.git;
git clone https://github.com/timlev/Learning-English-HTML.git;
cd Learning-English-HTML;
git checkout -b gh-pages origin/gh-pages;
cd ~/GitProjects;
git clone https://github.com/timlev/read-story.git;
cd read-story;
git checkout -b gh-pages origin/gh-pages;